[workspace]
resolver = "2"

members = [
    "payment-stream",
    "distributor",
    "nft-stream",
    "libs/common",
    "campaign-funding",
    "soulbound-badge",
    "verifier-penalty",
    "planter",
    "dispute-arbiter",
    "timelock",
    "upgrade-proxy",
    "sponsor-crowdfunding",
    "sponsor-insurance",
    "donor-verification",
]

[workspace.package]
version = "0.1.0"
edition = "2021"
license = "MIT"
repository = "https://github.com/Fundable-Protocol/stellar_client"

[workspace.dependencies]
soroban-sdk = "=25.3.2"
contract-common = { path = "libs/common" }

[profile.release]
opt-level = "z"
overflow-checks = true
debug = 0
strip = "symbols"
debug-assertions = false
panic = "abort"
codegen-units = 1
lto = true

[profile.release-with-logs]
inherits = "release"
debug-assertions = true
